### ISSUE TITLE
Repo name is wrong

### ISSUE THREAD

**Issue by realvikas** [shadmansaleh/colorscheme_generator.nvim#2]

**Comment by shadmansaleh** [comment]
Sorry . Can you describe the issue ?

**Comment by realvikas** [comment]
Repository name is `colorsceme_generator.nvim` it should be `colorscheme_generator.nvim`.

**Comment by shadmansaleh** [comment]
Thanks for letting me know . I've fixed that . Funny thung since I wrote the links in readme by hand they are colorscheme_generator.nvim :}
